import { OverlayTool } from '@components/Overlaytool'
import '@styles/main.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import image from '@utils/overlayImages/image.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <OverlayTool image={image} /> */}
      <body>{children}</body>
    </html>
  )
}
