import '@styles/main.scss'
import { logoArt } from '@utils/art'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(logoArt)
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
